version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0-browsers
      - image: circleci/node:13.8.0
      - image: selenium/hub
        name: hub
      - image: selenium/node-chrome
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm run start
          background: true

      - run:
          name: Waiting for App server to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3000 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Selenium && exit 
   
      # run tests!
      - run: npm run test

      - store_artifacts:
          path: ./errorShots/
          when: always